schemaVersion: 2.1.0
metadata:
  name: nodejs-web-app
components:
  - name: tools
    container:
      image: docker-eu.artifactory.swg-devops.com/sys-chipdev-cloud-team-experimental-docker-local/jumpstart-cocofu:latest
      endpoints:
        - exposure: public
          name: nodejs
          protocol: http
          targetPort: 3000
      memoryLimit: 1G
      mountSources: true
